Repository Team-Koreano/Koreano, pull requests merged in 2024-06, with the labels that each got.

#171 [회원] 회원 리팩토링
  .idea/gradle.xml
  user-api/src/main/java/org/ecommerce/userapi/client/PaymentServiceClient.java
  user-api/src/main/java/org/ecommerce/userapi/client/SellerServiceClient.java
  user-api/src/main/java/org/ecommerce/userapi/client/UserServiceClient.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AccountDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AccountMapper.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AddressDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AddressMapper.java
  user-api/src/main/java/org/ecommerce/userapi/dto/BeanPayDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/SellerDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/SellerMapper.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserMapper.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/CreateAccountRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/CreateAddressRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/CreateBeanPayRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/CreateSellerRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/CreateUserRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/DeleteBeanPayRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/LoginSellerRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/LoginUserRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/WithdrawalSellerRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/WithdrawalUserRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/response/CreateAccountResponse.java
  user-api/src/main/java/org/ecommerce/userapi/dto/response/CreateAddressResponse.java
  user-api/src/main/java/org/ecommerce/userapi/dto/response/CreateSellerResponse.java
  user-api/src/main/java/org/ecommerce/userapi/dto/response/CreateUserResponse.java
  user-api/src/main/java/org/ecommerce/userapi/dto/response/LoginSellerResponse.java
  user-api/src/main/java/org/ecommerce/userapi/dto/response/LoginUserResponse.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Seller.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Users.java
  user-api/src/main/java/org/ecommerce/userapi/exception/UserErrorCode.java
  user-api/src/main/java/org/ecommerce/userapi/exception/UserErrorMessages.java
  user-api/src/main/java/org/ecommerce/userapi/external/controller/SellerController.java
  user-api/src/main/java/org/ecommerce/userapi/external/controller/UserController.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/SellerService.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/UserService.java
  user-api/src/main/java/org/ecommerce/userapi/repository/AddressCustomRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/SellerCustomAccountRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/SellerCustomRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UserAccountCustomRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UserCustomRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/AddressRepositoryImpl.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/SellerAccountRepositoryImpl.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/SellerRepositoryImpl.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/UserAccountRepositoryImpl.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/UserRepositoryImpl.java
  user-api/src/test/java/org/ecommerce/userapi/controller/SellerControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/controller/UserControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/SellerDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/UserDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/SellerServiceTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/UserServiceTest.java
Labels: 개발, 회원, 리팩토링

#181 [상품] 상품 리팩토링
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ImageDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementMapper.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductWithSellerRepAndImagesDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductWithSellerRepDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/SellerRepDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/request/CreateProductRequest.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/request/ModifyProductRequest.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/request/ModifyProductsStatusRequest.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/request/ModifyStockRequest.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/response/CategoryResponse.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/response/ImageResponse.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/response/ProductResponse.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/exception/ProductManagementErrorMessages.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/external/ProductManagementController.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/external/ProductManagementService.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/provider/S3Provider.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/impl/ProductRepositoryImpl.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/controller/ExternalProductManagementControllerTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/dto/ProductManagementDtoTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/service/ProductManagementServiceTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/external/controller/ProductSearchControllerTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/external/service/ProductSearchServiceTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/internal/controller/ProductSearchControllerTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/internal/service/ProductSearchServiceTest.java
  product/src/main/java/org/ecommerce/product/entity/Product.java
Labels: 상품, 리팩토링

#182 [결제] 빈페이 삭제
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/DeleteBeanPayRequest.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/BeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/BeanPayErrorCode.java
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/service/BeanPayService.java
  payment-api/src/main/resources/data.sql
  payment-api/src/test/java/org/ecommerce/paymentapi/dto/PaymentDetailDtoTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/BeanPayServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/LockTestServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/controller/PaymentControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/service/BeanPayServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/service/PaymentServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/BeanPayRepositoryTest.java
Labels: 개발, 결제

#185 [결제] 빈페이 테이블 리펙토링
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  payment-api/src/main/java/org/ecommerce/paymentapi/aop/DistributedLock.java
  payment-api/src/main/java/org/ecommerce/paymentapi/aop/DistributedLockAop.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/BeanPayMapper.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/DeleteBeanPayRequest.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/PaymentDetailMapper.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/PaymentMapper.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/SellerBeanPayDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/SellerBeanPayMapper.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/UserBeanPayDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/UserBeanPayMapper.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/request/CreateSellerBeanPayRequest.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/request/CreateUserBeanPayRequest.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/request/DeleteSellerBeanPayRequest.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/request/DeleteUserBeanPayRequest.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/response/SellerBeanPayResponse.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/response/UserBeanPayResponse.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/Payment.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/PaymentDetail.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/SellerBeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/UserBeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/LockName.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/Role.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/BeanPayErrorMessage.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/service/BeanPayService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/service/LockTestService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/service/BeanPayService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/service/PaymentService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/BeanPayCustomRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/SellerBeanPayCustomRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/SellerBeanPayRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/UserBeanPayCustomRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/UserBeanPayRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/impl/BeanPayRepositoryImpl.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/impl/SellerBeanPayRepositoryImpl.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/impl/UserBeanPayRepositoryImpl.java
  payment-api/src/test/java/org/ecommerce/paymentapi/dto/PaymentDetailDtoTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/BeanPayIntegrationServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/BeanPayServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/LockTestServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/controller/PaymentControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/service/PaymentServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/service/UserBeanPayServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/BeanPayRepositoryTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/UserBeanPayRepositoryTest.java
Labels: 결제, 리팩토링

#189 [리팩토링] 회원 빈페이 등록, 삭제 로직 수정
  user-api/src/main/java/org/ecommerce/userapi/client/PaymentServiceClient.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/CreateSellerBeanPayRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/CreateUserBeanPayRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/DeleteSellerBeanPayRequest.java
  user-api/src/main/java/org/ecommerce/userapi/dto/request/DeleteUserBeanPayRequest.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/SellerService.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/UserService.java
  user-api/src/test/java/org/ecommerce/userapi/service/SellerServiceTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/UserServiceTest.java
  user-api/src/test/resources/application.yml
Labels: 회원, 리팩토링

#191 [결제] 유저 빈페이 내역 조회
  .idea/gradle.xml
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/SellerBeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/UserBeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/PaymentStatus.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/controller/PaymentDetailController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/service/PaymentDetailReadService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/PaymentDetailCustomRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/impl/PaymentDetailRepositoryImpl.java
  payment-api/src/main/java/org/ecommerce/paymentapi/utils/PaymentTimeFormatUtil.java
  payment-api/src/main/resources/data.sql
  payment-api/src/test/java/org/ecommerce/paymentapi/PaymentApiApplicationTests.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/controller/PaymentDetailControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/BeanPayIntegrationServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/LockTestServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/PaymentDetailReadServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/controller/PaymentControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/service/PaymentDetailReadServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/UserBeanPayRepositoryTest.java
  payment-api/src/test/resources/junit-platform.properties
Labels: 개발, 결제
