Repository Team-Koreano/Koreano, pull requests merged in 2024-05, with the labels that each got.

#111 주문에 대한 재고 처리
  order-api/src/main/java/org/ecommerce/orderapi/client/BucketServiceClient.java
  order-api/src/main/java/org/ecommerce/orderapi/client/RedisClient.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/OrderDetail.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/OrderStatusHistory.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/Product.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/Stock.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/StockHistory.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/type/ProductStatus.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/type/StockOperationType.java
  order-api/src/main/java/org/ecommerce/orderapi/exception/OrderErrorCode.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/StockHistoryRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/service/OrderService.java
  order-api/src/main/java/org/ecommerce/orderapi/service/ProductService.java
  order-api/src/main/java/org/ecommerce/orderapi/service/StockService.java
Labels: 개발, 주문, 리팩토링

#121 [코드리뷰 반영] 유저 리팩토링
  build.gradle
  user-api/build.gradle
  user-api/gradlew
  user-api/gradlew.bat
  user-api/settings.gradle
  user-api/src/main/java/org/ecommerce/userapi/UserApiApplication.java
  user-api/src/main/java/org/ecommerce/userapi/config/BeanConfiguration.java
  user-api/src/main/java/org/ecommerce/userapi/config/WebMvcConfig.java
  user-api/src/main/java/org/ecommerce/userapi/dto/SellerDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserDto.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Member.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Seller.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Users.java
  user-api/src/main/java/org/ecommerce/userapi/entity/enumerated/Gender.java
  user-api/src/main/java/org/ecommerce/userapi/entity/enumerated/Role.java
  user-api/src/main/java/org/ecommerce/userapi/entity/enumerated/UserStatus.java
  user-api/src/main/java/org/ecommerce/userapi/exception/UserErrorCode.java
  user-api/src/main/java/org/ecommerce/userapi/external/controller/SellerController.java
  user-api/src/main/java/org/ecommerce/userapi/external/controller/UserController.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/SellerService.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/UserService.java
  user-api/src/main/java/org/ecommerce/userapi/repository/SellerRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UserRepository.java
  user-api/src/main/java/org/ecommerce/userapi/security/AuthDetails.java
  user-api/src/main/java/org/ecommerce/userapi/security/AuthDetailsService.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtFilter.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtProvider.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtUtils.java
  user-api/src/main/java/org/ecommerce/userapi/security/WebSecurity.java
  user-api/src/main/java/org/ecommerce/userapi/security/custom/CurrentUser.java
  user-api/src/main/java/org/ecommerce/userapi/security/custom/CurrentUserArgumentResolver.java
  user-api/src/main/resources/application.yml
  user-api/src/test/java/org/ecommerce/userapi/controller/SellerControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/controller/UserControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/SellerDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/UserDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/SellerServiceTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/UserServiceTest.java
Labels: 개발, 회원, 리팩토링

#128 [결제 파트] QueryDSL 적용 및 리펙토링
  build.gradle
  payment-api/.gitignore
  payment-api/build.gradle
  payment-api/settings.gradle
  payment-api/src/main/java/org/ecommerce/paymentapi/config/QueryDslConfig.java
  payment-api/src/main/java/org/ecommerce/paymentapi/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/BeanPayDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/BeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/BeanPayDetail.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/RefundDetail.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/BeanPayStatus.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/PaymentStatus.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/ProcessStatus.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/RefundStatus.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/Role.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/BeanPayDetailErrorCode.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/BeanPayErrorCode.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/BeanPayCustomRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/BeanPayRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/impl/BeanPayRepositoryImpl.java
  payment-api/src/main/java/org/ecommerce/paymentapi/service/BeanPayService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/service/LockTestService.java
  payment-api/src/test/java/org/ecommerce/paymentapi/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/entity/BeanPayDetailTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/BeanPayDetailRepositoryTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/BeanPayRepositoryTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/service/BeanPayDetailServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/service/LockTestServiceTest.java
Labels: 결제, 리팩토링

#131 [코드리뷰 반영]Product Management 리팩토링
  product-management-api/build.gradle
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/ProductManagementApiApplication.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/aop/TimeCheck.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/aop/TimeCheckAop.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/config/S3Config.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/exception/ProductManagementErrorCode.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/external/ProductManagementController.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/external/ProductManagementService.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/provider/S3Provider.java
  product-management-api/src/main/resources/application.yml
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/ProductManagementApiApplicationTests.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/config/MockS3Config.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/controller/ProductManagementControllerTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/dto/ProductManagementDtoTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/service/ProductManagementServiceTest.java
  product-management-api/src/test/resources/application.yml
Labels: 개발, 상품

#139 [주문] 주문 취소, 재고 증가
  order-api/src/main/java/org/ecommerce/orderapi/dto/OrderDetailDto.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/OrderDetail.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/Stock.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/StockHistory.java
  order-api/src/main/java/org/ecommerce/orderapi/exception/OrderErrorCode.java
  order-api/src/main/java/org/ecommerce/orderapi/exception/StockErrorCode.java
  order-api/src/main/java/org/ecommerce/orderapi/external/controller/OrderController.java
  order-api/src/main/java/org/ecommerce/orderapi/internal/controller/StockController.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/OrderDetailCustomRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/StockHistoryCustomRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/StockHistoryRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/impl/OrderDetailRepositoryImpl.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/impl/StockHistoryRepositoryImpl.java
  order-api/src/main/java/org/ecommerce/orderapi/service/OrderService.java
  order-api/src/main/java/org/ecommerce/orderapi/service/StockService.java
  order-api/src/main/java/org/ecommerce/orderapi/util/OrderPolicyConstants.java
  order-api/src/test/java/org/ecommerce/orderapi/external/controller/OrderControllerTest.java
  order-api/src/test/java/org/ecommerce/orderapi/internal/controller/StockControllerTest.java
  order-api/src/test/java/org/ecommerce/orderapi/service/OrderServiceTest.java
  order-api/src/test/java/org/ecommerce/orderapi/service/StockServiceTest.java
Labels: 개발, 주문

#136 주문 조회 기능 구현
  order-api/src/main/java/org/ecommerce/orderapi/client/UserServiceClient.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/BucketSummary.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/OrderDetailDto.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/OrderDetailMapper.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/OrderDto.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/OrderMapper.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/OrderStatusHistoryDto.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/ProductDto.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/UserDto.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/UserMapper.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/Order.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/OrderDetail.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/OrderStatusHistory.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/Product.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/Stock.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/StockHistory.java
  order-api/src/main/java/org/ecommerce/orderapi/entity/User.java
  order-api/src/main/java/org/ecommerce/orderapi/exception/OrderErrorCode.java
  order-api/src/main/java/org/ecommerce/orderapi/exception/StockErrorCode.java
  order-api/src/main/java/org/ecommerce/orderapi/external/controller/OrderController.java
  order-api/src/main/java/org/ecommerce/orderapi/internal/controller/StockController.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/OrderCustomRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/OrderDetailCustomRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/OrderStatusHistoryCustomRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/OrderStatusHistoryRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/StockHistoryCustomRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/StockHistoryRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/impl/OrderDetailRepositoryImpl.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/impl/OrderRepositoryImpl.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/impl/OrderStatusHistoryRepositoryImpl.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/impl/StockHistoryRepositoryImpl.java
  order-api/src/main/java/org/ecommerce/orderapi/service/OrderService.java
  order-api/src/main/java/org/ecommerce/orderapi/service/StockService.java
  order-api/src/main/java/org/ecommerce/orderapi/util/OrderPolicyConstants.java
  order-api/src/main/resources/application.yml
  order-api/src/main/resources/data.sql
  order-api/src/test/java/org/ecommerce/orderapi/external/controller/OrderControllerTest.java
  order-api/src/test/java/org/ecommerce/orderapi/internal/controller/StockControllerTest.java
  order-api/src/test/java/org/ecommerce/orderapi/service/OrderServiceTest.java
  order-api/src/test/java/org/ecommerce/orderapi/service/StockServiceTest.java
  order-api/src/test/resources/application.yml
Labels: 개발, 주문

#138 유저 리팩토링
  user-api/build.gradle
  user-api/src/main/java/org/ecommerce/userapi/config/BeanConfiguration.java
  user-api/src/main/java/org/ecommerce/userapi/config/QueryDslConfig.java
  user-api/src/main/java/org/ecommerce/userapi/config/WebMvcConfig.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AccountDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AccountMapper.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AddressDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AddressMapper.java
  user-api/src/main/java/org/ecommerce/userapi/dto/SellerDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/SellerMapper.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserMapper.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Address.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Users.java
  user-api/src/main/java/org/ecommerce/userapi/entity/UsersAccount.java
  user-api/src/main/java/org/ecommerce/userapi/exception/UserErrorCode.java
  user-api/src/main/java/org/ecommerce/userapi/external/controller/SellerController.java
  user-api/src/main/java/org/ecommerce/userapi/external/controller/UserController.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/SellerService.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/UserService.java
  user-api/src/main/java/org/ecommerce/userapi/provider/RedisProvider.java
  user-api/src/main/java/org/ecommerce/userapi/repository/AddressCustomRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/AddressRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/SellerAccountRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/SellerCustomRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/SellerRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UserAccountCustomRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UserCustomRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UserRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UsersAccountRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/AddressRepositoryImpl.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/SellerRepositoryImpl.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/UserAccountRepositoryImpl.java
  user-api/src/main/java/org/ecommerce/userapi/repository/impl/UserRepositoryImpl.java
  user-api/src/main/java/org/ecommerce/userapi/security/AuthDetails.java
  user-api/src/main/java/org/ecommerce/userapi/security/CustomAuthProvider.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtFilter.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtProvider.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtUtils.java
  user-api/src/main/java/org/ecommerce/userapi/security/custom/CurrentUserArgumentResolver.java
  user-api/src/test/java/org/ecommerce/userapi/controller/SellerControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/controller/UserControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/SellerDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/UserDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/SellerServiceTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/UserServiceTest.java
Labels: 개발, 회원, 리팩토링

#149 상품 카테고리별 등록 로직 구현
  order-api/src/test/java/org/ecommerce/orderapi/service/OrderServiceTest.java
  product-management-api/build.gradle
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/config/QueryDslConfig.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementMapper.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/exception/ProductManagementErrorCode.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/exception/ProductManagementErrorMessages.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/external/ProductManagementController.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/external/ProductManagementService.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/ImageCustomRepository.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/ImageRepository.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/ProductCustomRepository.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/ProductRepository.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/impl/ImageRepositoryImpl.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/impl/ProductRepositoryImpl.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/util/ProductFactory.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/controller/ExternalProductManagementControllerTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/dto/ProductManagementDtoTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/service/ProductManagementServiceTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/external/controller/ProductSearchControllerTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/external/service/ProductSearchServiceTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/internal/controller/ProductSearchControllerTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/internal/service/ProductSearchServiceTest.java
  product/src/main/java/org/ecommerce/product/entity/Product.java
Labels: 개발, 상품, 리팩토링

#150 [결제] Spring AOP List 가변 락 적용
  payment-api/src/main/java/org/ecommerce/paymentapi/aop/CustomSpringELParser.java
  payment-api/src/main/java/org/ecommerce/paymentapi/aop/DistributedLock.java
  payment-api/src/main/java/org/ecommerce/paymentapi/aop/DistributedLockAop.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/BeanPayDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/PaymentDetailDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/PaymentDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/PaymentMapper.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/PaymentDetail.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/enumerate/LockName.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/service/BeanPayService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/service/LockTestService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/service/PaymentService.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/LockTestServiceTest.java
Labels: 개발, 결제

#155 Feign Client 를 통한 빈페이 생성로직 구현
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/controller/BeanPayController.java
  payment-api/src/main/resources/data.sql
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/controller/BeanPayControllerTest.java
  user-api/src/main/java/org/ecommerce/userapi/UserApiApplication.java
  user-api/src/main/java/org/ecommerce/userapi/client/SellerServiceClient.java
  user-api/src/main/java/org/ecommerce/userapi/client/UserServiceClient.java
  user-api/src/main/java/org/ecommerce/userapi/dto/BeanPayDto.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Seller.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Users.java
  user-api/src/main/java/org/ecommerce/userapi/exception/UserErrorMessages.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/SellerService.java
  user-api/src/main/java/org/ecommerce/userapi/external/service/UserService.java
  user-api/src/main/resources/application.yml
  user-api/src/test/java/org/ecommerce/userapi/controller/SellerControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/controller/UserControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/SellerDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/UserDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/SellerServiceTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/UserServiceTest.java
  user-api/src/test/resources/application.yml
Labels: 개발, 회원

#161 [상품] 상품 리팩토링
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementMapper.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/exception/ProductManagementErrorCode.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/external/ProductManagementService.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/provider/S3Provider.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/ProductCustomRepository.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/impl/ProductRepositoryImpl.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/util/FileUtils.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/util/ProductFactory.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/controller/ExternalProductManagementControllerTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/dto/ProductManagementDtoTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/service/ProductManagementServiceTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/external/controller/ProductSearchControllerTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/external/service/ProductSearchServiceTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/internal/controller/ProductSearchControllerTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/internal/service/ProductSearchServiceTest.java
  product/src/main/java/org/ecommerce/product/entity/Product.java
  product/src/main/java/org/ecommerce/product/entity/enumerated/Acidity.java
  product/src/main/java/org/ecommerce/product/entity/enumerated/Bean.java
Labels: 상품, 리팩토링

#165 [리팩토링] 상품 리스트 검색 로직
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/controller/ExternalProductManagementControllerTest.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/document/ProductDocument.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/dto/ProductSearchDto.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/enumerated/ProductDocumentField.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/enumerated/ProductSortType.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/repository/impl/ProductElasticsearchRepositoryImpl.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/external/controller/ProductSearchControllerTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/external/service/ElasticSearchServiceTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/internal/controller/ProductSearchControllerTest.java
Labels: 상품, 리팩토링

#169 [결제] 결제로직 리펙토링
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/PaymentDetailDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/PaymentDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/PaymentMapper.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/ChargeInfo.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/Payment.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/PaymentDetail.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/PreTossPaymentFail.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/Refund.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/RefundDetail.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/PaymentDetailErrorMessage.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/PaymentErrorCode.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/controller/TestController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/service/BeanPayService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/external/service/LockTestService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/service/BeanPayService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/internal/service/PaymentService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/BeanPayCustomRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/PaymentCustomRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/PaymentDetailCustomRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/PreTossPaymentFailRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/RefundDetailRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/RefundRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/impl/BeanPayRepositoryImpl.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/impl/PaymentDetailRepositoryImpl.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/impl/PaymentRepositoryImpl.java
  payment-api/src/main/resources/application-local.yml
  payment-api/src/main/resources/application-test.yml
  payment-api/src/main/resources/data.sql
  payment-api/src/test/java/org/ecommerce/paymentapi/dto/PaymentDetailDtoTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/BeanPayIntegrationServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/BeanPayServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/external/service/LockTestServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/controller/PaymentControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/service/BeanPayServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/internal/service/PaymentServiceTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/BeanPayRepositoryTest.java
  product/src/main/java/org/ecommerce/product/ProductApplication.java
Labels: 결제, 리팩토링
