Repository Team-Koreano/Koreano, pull requests merged in 2024-04, with the labels that each got.

#7 #4 test: 테스트 커밋
  payment-api/src/main/java/org/ecommerce/paymentapi/PaymentApiApplication.java
Labels: 테스트

#14 User MVC 계층 구조 설계
  build.gradle
  user-api/src/main/java/org/ecommerce/userapi/controller/UserController.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserDto.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Address.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Favorite.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Seller.java
  user-api/src/main/java/org/ecommerce/userapi/entity/SellerAccount.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Users.java
  user-api/src/main/java/org/ecommerce/userapi/entity/UsersAccount.java
  user-api/src/main/java/org/ecommerce/userapi/entity/type/Gender.java
  user-api/src/main/java/org/ecommerce/userapi/entity/type/Status.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UserRepository.java
  user-api/src/main/java/org/ecommerce/userapi/service/UserService.java
  user-api/src/main/resources/application.properties
  user-api/src/main/resources/application.yml
Labels: 회원

#25 유저 모듈 컨벤션에 맞게 리팩토링 작업
  user-api/src/main/java/org/ecommerce/userapi/controller/UserController.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserDto.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Address.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Favorite.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Seller.java
  user-api/src/main/java/org/ecommerce/userapi/entity/SellerAccount.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Users.java
  user-api/src/main/java/org/ecommerce/userapi/entity/UsersAccount.java
  user-api/src/main/java/org/ecommerce/userapi/entity/type/UserStatus.java
  user-api/src/main/java/org/ecommerce/userapi/service/UserService.java
Labels: 개발, 회원

#30 장바구니 조회 기능 구현
  bucket-api/src/main/java/org/ecommerce/bucketapi/controller/BucketController.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/dto/BucketDTO.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/entity/Bucket.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/repository/BucketRepository.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/service/BucketService.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/controller/BucketControllerTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/dto/BucketDtoTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/service/BucketServiceTest.java
Labels: 개발, 장바구니

#39 장바구니 등록 API 개발 #35
  bucket-api/src/main/java/org/ecommerce/bucketapi/BucketApiApplication.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/controller/BucketController.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/dto/BucketDTO.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/dto/BucketDto.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/entity/Bucket.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/exception/BucketErrorCode.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/repository/BucketRepository.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/service/BucketService.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/controller/BucketControllerTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/dto/BucketDtoTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/service/BucketServiceTest.java
  build.gradle
  common/src/main/java/org/ecommerce/common/advice/GlobalExceptionHandler.java
Labels: 개발, 장바구니

#47 장바구니 수정 API 개발 #40
  .idea/gradle.xml
  bucket-api/src/main/java/org/ecommerce/bucketapi/controller/BucketController.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/dto/BucketDto.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/entity/Bucket.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/exception/BucketErrorCode.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/repository/BucketRepository.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/service/BucketService.java
  bucket-api/src/main/resources/data.sql
  bucket-api/src/test/java/org/ecommerce/bucketapi/controller/BucketControllerTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/dto/BucketDtoTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/entity/BucketTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/service/BucketServiceTest.java
Labels: 개발, 장바구니

#52 회원 로그인 API 개발
  build.gradle
  user-api/src/main/java/org/ecommerce/userapi/config/BeanConfiguration.java
  user-api/src/main/java/org/ecommerce/userapi/config/JasyptConfig.java
  user-api/src/main/java/org/ecommerce/userapi/config/RedisConfig.java
  user-api/src/main/java/org/ecommerce/userapi/controller/SellerController.java
  user-api/src/main/java/org/ecommerce/userapi/controller/UserController.java
  user-api/src/main/java/org/ecommerce/userapi/dto/SellerDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserDto.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Member.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Seller.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Users.java
  user-api/src/main/java/org/ecommerce/userapi/entity/type/Role.java
  user-api/src/main/java/org/ecommerce/userapi/exception/UserErrorCode.java
  user-api/src/main/java/org/ecommerce/userapi/repository/SellerRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UserRepository.java
  user-api/src/main/java/org/ecommerce/userapi/security/AuthDetails.java
  user-api/src/main/java/org/ecommerce/userapi/security/AuthDetailsService.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtFilter.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtProvider.java
  user-api/src/main/java/org/ecommerce/userapi/security/JwtUtils.java
  user-api/src/main/java/org/ecommerce/userapi/security/SecurityKeyConfig.java
  user-api/src/main/java/org/ecommerce/userapi/security/WebSecurity.java
  user-api/src/main/java/org/ecommerce/userapi/service/SellerService.java
  user-api/src/main/java/org/ecommerce/userapi/service/UserService.java
  user-api/src/main/java/org/ecommerce/userapi/utils/RedisUtils.java
  user-api/src/main/resources/application.yml
  user-api/src/test/java/org/ecommerce/userapi/controller/SellerControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/controller/UserControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/SellerServiceTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/UserServiceTest.java
  user-api/src/test/resources/application.yml
Labels: 개발, 회원

#55 토스결제검증 로직 작성 #46
  .idea/gradle.xml
  build.gradle
  payment-api/src/main/java/org/ecommerce/paymentapi/client/TossServiceClient.java
  payment-api/src/main/java/org/ecommerce/paymentapi/config/ConfigProperties.java
  payment-api/src/main/java/org/ecommerce/paymentapi/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/BeanPayDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/BeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/BeanPayErrorCode.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/BeanPayRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/service/BeanPayService.java
  payment-api/src/main/java/org/ecommerce/paymentapi/utils/BeanPayTimeFormatUtil.java
  payment-api/src/main/java/org/ecommerce/paymentapi/utils/TossKey.java
  payment-api/src/main/resources/application.yml
  payment-api/src/test/java/org/ecommerce/paymentapi/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/dto/BeanPayDtoTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/entity/BeanPayTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/service/BeanPayServiceTest.java
Labels: 개발, 결제

#63 주문 생성 Service - 장바구니에 담긴 상품 Info를 가져오는 API 구현
  bucket-api/src/main/generated/org/ecommerce/bucketapi/dto/BucketMapperImpl.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/controller/BucketController.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/service/BucketService.java
  build.gradle
  order-api/src/main/java/org/ecommerce/orderapi/OrderApiApplication.java
  order-api/src/main/java/org/ecommerce/orderapi/client/BucketServiceClient.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/BucketDto.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/BucketMapper.java
  order-api/src/main/java/org/ecommerce/orderapi/dto/OrderDto.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/OrderDetailRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/repository/OrderRepository.java
  order-api/src/main/java/org/ecommerce/orderapi/service/OrderService.java
  order-api/src/main/resources/application.yml
Labels: 개발, 주문, 장바구니

#64 회원 주소, 셀러와 회원 계좌 Create API 구현
  build.gradle
  user-api/src/main/generated/org/ecommerce/userapi/dto/SellerMapperImpl.java
  user-api/src/main/generated/org/ecommerce/userapi/dto/UserMapperImpl.java
  user-api/src/main/java/org/ecommerce/userapi/controller/SellerController.java
  user-api/src/main/java/org/ecommerce/userapi/controller/UserController.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AccountDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AccountMapper.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AddressDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/AddressMapper.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Address.java
  user-api/src/main/java/org/ecommerce/userapi/entity/SellerAccount.java
  user-api/src/main/java/org/ecommerce/userapi/entity/UsersAccount.java
  user-api/src/main/java/org/ecommerce/userapi/repository/AddressRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/SellerAccountRepository.java
  user-api/src/main/java/org/ecommerce/userapi/repository/UsersAccountRepository.java
  user-api/src/main/java/org/ecommerce/userapi/service/SellerService.java
  user-api/src/main/java/org/ecommerce/userapi/service/UserService.java
  user-api/src/test/java/org/ecommerce/userapi/controller/SellerControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/controller/UserControllerTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/SellerServiceTest.java
  user-api/src/test/java/org/ecommerce/userapi/service/UserServiceTest.java
Labels: 개발, 회원

#66 토스 사전충전실패 API 구현
  payment-api/src/main/java/org/ecommerce/paymentapi/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/BeanPayDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/BeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/service/BeanPayService.java
  payment-api/src/test/java/org/ecommerce/paymentapi/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/dto/BeanPayDtoTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/entity/BeanPayTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/service/BeanPayServiceTest.java
Labels: 개발, 결제, 리팩토링

#82 [도영님 의견반영 리펙토링] 결제파트 리펙토링 및 yml파일 분리 및 jasypt적용
  payment-api/src/main/java/org/ecommerce/paymentapi/PaymentApiApplication.java
  payment-api/src/main/java/org/ecommerce/paymentapi/client/TossServiceClient.java
  payment-api/src/main/java/org/ecommerce/paymentapi/config/ConfigProperties.java
  payment-api/src/main/java/org/ecommerce/paymentapi/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/BeanPayDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/TossDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/BeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/BeanPayErrorMessage.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/TossErrorMessage.java
  payment-api/src/main/java/org/ecommerce/paymentapi/service/BeanPayService.java
  payment-api/src/main/resources/application-local.yml
  payment-api/src/main/resources/application.yml
  payment-api/src/test/java/org/ecommerce/paymentapi/PaymentApiApplicationTests.java
  payment-api/src/test/java/org/ecommerce/paymentapi/controller/BeanPayControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/dto/BeanPayDtoTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/dto/TossDtoTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/entity/BeanPayTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/service/BeanPayServiceTest.java
Labels: 결제, 리팩토링

#95 ProductManagement #65 Conflict 해결
  build.gradle
  product-management-api/src/main/generated/org/ecommerce/productmanagementapi/dto/ProductManagementMapperImpl.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/ProductManagementApiApplication.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/controller/ProductManagementController.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementMapper.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/exception/ProductManagementErrorMessages.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/ImageRepository.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/ProductRepository.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/repository/SellerRepository.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/service/ProductManagementService.java
  product-management-api/src/main/resources/application.properties
  product-management-api/src/main/resources/application.yml
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/ProductManagementApiApplicationTests.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/controller/ProductManagementControllerTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/dto/ProductManagementDtoTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/service/ProductManagementServiceTest.java
  product-management-api/src/test/resources/application.yml
Labels: 버그, 리팩토링

#83 FeignException 처리 및 예시코드
  build.gradle
  common/src/main/java/org/ecommerce/common/advice/GlobalExceptionHandler.java
  common/src/main/java/org/ecommerce/common/config/FeignConfig.java
  common/src/main/java/org/ecommerce/common/error/CustomErrorDecoder.java
  common/src/main/java/org/ecommerce/common/error/FeignErrorCode.java
  order-api/src/main/java/org/ecommerce/orderapi/client/BucketServiceClient.java
Labels: 개발, 주문, 공통

#87 [리뷰 반영] 장바구니 Refactoring
  bucket-api/src/main/generated/org/ecommerce/bucketapi/dto/BucketMapperImpl.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/controller/ExternalBucketController.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/controller/InternalBucketController.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/dto/BucketDto.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/dto/BucketMapper.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/entity/Bucket.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/exception/BucketErrorCode.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/exception/ErrorMessage.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/repository/BucketRepository.java
  bucket-api/src/main/java/org/ecommerce/bucketapi/service/BucketService.java
  bucket-api/src/main/resources/application-local.yml
  bucket-api/src/main/resources/application.yml
  bucket-api/src/test/java/org/ecommerce/bucketapi/controller/ExternalBucketControllerTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/controller/InternalBucketControllerTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/dto/BucketDtoTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/entity/BucketTest.java
  bucket-api/src/test/java/org/ecommerce/bucketapi/service/BucketServiceTest.java
Labels: 장바구니, 리팩토링

#90 [결제파트] Refactor BeanPay 구조 변경
  build.gradle
  payment-api/src/main/java/org/ecommerce/paymentapi/PaymentApiApplication.java
  payment-api/src/main/java/org/ecommerce/paymentapi/controller/BeanPayController.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/BeanPayDto.java
  payment-api/src/main/java/org/ecommerce/paymentapi/dto/BeanPayMapper.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/BeanPay.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/BeanPayDetail.java
  payment-api/src/main/java/org/ecommerce/paymentapi/entity/type/ProcessStatus.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/BeanPayDetailErrorCode.java
  payment-api/src/main/java/org/ecommerce/paymentapi/exception/BeanPayErrorCode.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/BeanPayDetailRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/repository/BeanPayRepository.java
  payment-api/src/main/java/org/ecommerce/paymentapi/service/BeanPayService.java
  payment-api/src/main/resources/application-dev.yml
  payment-api/src/main/resources/application.yml
  payment-api/src/test/java/org/ecommerce/paymentapi/controller/BeanPayDetailControllerTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/dto/BeanPayDetailDtoTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/entity/BeanPayDetailTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/BeanPayDetailRepositoryTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/repository/BeanPayRepositoryTest.java
  payment-api/src/test/java/org/ecommerce/paymentapi/service/BeanPayDetailServiceTest.java
Labels: 결제, 리팩토링

#97 [코드리뷰 반영] 상품 단일 조회 리팩토링
  product-search-api/.gitignore
  product-search-api/src/main/generated/org/ecommerce/productsearchapi/dto/ProductMapperImpl.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/dto/ImageDto.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/dto/ProductMapper.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/dto/ProductSearchDto.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/repository/ProductCustomRepository.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/repository/ProductRepository.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/repository/SellerRepository.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/repository/impl/ProductRepositoryImpl.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/repository/querydsl/ProductCustomRepositoryImpl.java
  product-search-api/src/main/java/org/ecommerce/productsearchapi/service/ProductSearchService.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/controller/ProductSearchControllerTest.java
  product-search-api/src/test/java/org/ecommerce/productsearchapi/service/ProductSearchServiceTest.java
  product/.gitignore
  product/src/main/java/org/ecommerce/product/entity/Image.java
  product/src/main/java/org/ecommerce/product/entity/Product.java
Labels: 개발, 상품, 리팩토링

#101 QueryDsl Config 위치 이동
  product-search-api/src/main/java/org/ecommerce/productsearchapi/config/QueryDslConfig.java
Labels: 버그, 상품

#99 [유저 파트] 빈페이 컬럼 ID로 변경
  payment-api/src/main/generated/org/ecommerce/paymentapi/dto/BeanPayMapperImpl.java
  payment-api/src/main/java/org/ecommerce/paymentapi/PaymentApiApplication.java
  product/.gitignore
  user-api/src/main/java/org/ecommerce/userapi/dto/SellerDto.java
  user-api/src/main/java/org/ecommerce/userapi/dto/UserDto.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Seller.java
  user-api/src/main/java/org/ecommerce/userapi/entity/Users.java
  user-api/src/test/java/org/ecommerce/userapi/dto/SellerDtoTest.java
  user-api/src/test/java/org/ecommerce/userapi/dto/UserDtoTest.java
Labels: 회원, 리팩토링

#106 상품 재고, 상태, 수정 로직 구현
  product-management-api/.gitignore
  product-management-api/src/main/generated/org/ecommerce/productmanagementapi/dto/ProductManagementMapperImpl.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/ProductManagementApiApplication.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/config/EnumConfig.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/config/EnumConverter.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/config/ScanConfig.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/controller/ExternalProductManagementController.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/controller/ProductManagementController.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementDto.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/dto/ProductManagementMapper.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/exception/ProductManagementErrorCode.java
  product-management-api/src/main/java/org/ecommerce/productmanagementapi/service/ProductManagementService.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/controller/ExternalProductManagementControllerTest.java
  product-management-api/src/test/java/org/ecommerce/productmanagementapi/service/ProductManagementServiceTest.java
  product/src/main/java/org/ecommerce/product/entity/Product.java
  product/src/main/java/org/ecommerce/product/entity/type/ProductStatus.java
Labels: 개발, 상품, 리팩토링

#114 Chore: 공통 의존성 분리
  build.gradle
  common/src/main/resources/application.yml
Labels: 리팩토링

#116 Chore: 공통모듈 제거
  build.gradle
Labels: 공통, 리팩토링
